//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_LTW_KinhDoanhLaptop
{
    public partial class TrangKhongTonTai
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblSoLuongGio;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divChuaDangNhap;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDaDangNhap;
        protected global::System.Web.UI.HtmlControls.HtmlImage imgAvatar;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTenTaiKhoan;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor linkQuanTri;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor linkThongKe;
    }
}
