//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_LTW_KinhDoanhLaptop
{


    public partial class TrangChu
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblSoLuongGio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSoLuongGio;

        /// <summary>
        /// divChuaDangNhap control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divChuaDangNhap;

        /// <summary>
        /// divDaDangNhap control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDaDangNhap;

        /// <summary>
        /// imgAvatar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage imgAvatar;

        /// <summary>
        /// lblTenTaiKhoan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTenTaiKhoan;

        /// <summary>
        /// linkQuanTri control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor linkQuanTri;

        /// <summary>
        /// linkThongKe control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor linkThongKe;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divVanPhong;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl khungVanPhong;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divGaming;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl khungGaming;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divMongNhe;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl khungMongNhe;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divSinhVien;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl khungSinhVien;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDoHoa;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl khungDoHoa;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCaoCap;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl khungCaoCap;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divKhongCoSP;
    }
}
